Translation
Hyperledger-TWGC/fabric-performance-wiki pull request #8
Opened 2021-01-26 20:53 UTC by lijiachuan1982

2021-01-27 11:59 UTC, SamYuan1990 requested changes

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +#Hyperledger Blockchain 性能指标 白皮书
空格？ 好像显示不太对
![Uploading image.png…]()

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +这个文档提供了一些关于如何选择和评估工作量的指南。我们期望这里谈到的这些定义以及新的针对于区块链特定的一些指标的改进在将来会被用来校订该文档。
workload 是不是可以翻译为负载？

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +
本文发布于October 2018. 版本 V1.01

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +虽然区块链可能看起来类似于分布式数据库，但它们通常在没有中央权威机构和中央存储库的情况下实现。因此，相对于以前的每件事情，区块链提供了一些独特的不同点。区块链通过在多个节点上使用冗余检查来避免故障和攻击。这种弹性远远超出了复制的能力，因为它是在没有任何中央协调者或中介的情况下横跨整个网络发生的。
因此，相较于中心化系统，区块链有很多新的特性。

Therefore blockchains provide some unique differences from everything that has come before.

replication 复制 -》 数据库之间的同步？ 因此翻译为同步是否合适？

它在没有任何中央协调者或中介的情况下横跨整个网络实现/运行的，因此这种弹性远远超出了复制的能力。

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +例如，在比特币中，最好的情况是，随着节点的增加，网络不会失去性能。
整体性能不至于降低。
the network would lose no performance as nodes are added.

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +当我们纵观区块链的时候，即使是这个简单的概念也可能变得复杂。一些区块链特定了节点的角色。在这些系统中，“节点”可能不再意味着具有共享的弹性职责的唯一参与者(比如作为一个公司)。
(比如，一家公司)。

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +这使得衡量和比较不同区块链之间的性能变得非常困难。为了帮助准确、一致地评估区块链的独特性能属性，本文定义了许多相关术语和指标，并讨论了一些复杂的问题。
issues这里是否可以翻译为情景？

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +_**测试工具**_ 是用于运行性能评估的硬件和软件。这个测试工具通常代表许多客户端，这些客户端可以注入工作负载并在任意数量的节点上进行观察。
注入负载 or 添加负载

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +_**客户端**_ 是可以将工作引入系统或调用系统行为的实体。在区块链系统中，通常在多个级别有多种类型的客户端。
级别？ 层面？层级？

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +_**负载生成器客户端**_ 是代表用户向区块链网络(SUT)提交交易的节点，通常遵循自动化测试脚本。客户端和SUT之间的接口可以从简单的Representational State Transfer (REST)接口到全面的软件开发工具包(SDK)。根据接口的不同，客户机可以是无状态的，也可以是有状态的。
代表/模拟

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +区块链是一项新技术，其命名方法每天都在形成和演进。许多常用的软件术语在描述区块链时有了新的细微差别。
是否可以对于这种来个加粗 斜体等方式加以强调？

2021-01-27 11:59 UTC, SamYuan1990 commented on performance-whitepaper.md
> +   For more details in the context of Hyperledger, please refer to the white paper on consensus, Volume I from the Hyperledger Architecture Working Group, available here.
英文？

2021-01-27 14:15 UTC, XuHugo commented on performance-whitepaper.md
> +试验结果应具有独立的可重复性。为了支持这一目标，所有的环境参数和测试软件，包括任何工作负载，都应该被记录下来并保证可用性。
建议重复改为复现，重现；比较恰当

2021-01-27 14:15 UTC, XuHugo commented on performance-whitepaper.md
> +本节讨论在设计任何区块链性能评估时的几个关键考虑事项，包括测试环境、观察点、交易特征、工作负载和故障负载。为了创建一个有效且可重复的设计，开发人员必须仔细权衡这些考虑因素，清楚地记录他们的决定，并充分报告他们的结果。
创建一个有效且可以复用的设计

2021-01-27 14:42 UTC, XuHugo commented on performance-whitepaper.md
> +性能基准测试活动应该在与网络运行环境类似的环境中进行。 即使在许可的区块链网络中，环境也会发生变化，从封闭的小规模网络到高度分布式的internet部署的网络。
internet：高分布式的公网

2021-01-27 14:47 UTC, XuHugo reviewed
ok

2021-01-27 15:47 UTC, lijiachuan1982 commented on performance-whitepaper.md
> +#Hyperledger Blockchain 性能指标 白皮书
你是指这个 H1 的标题显示的不太对吗？

2021-01-27 16:15 UTC, lijiachuan1982 commented on performance-whitepaper.md
> +_**负载生成器客户端**_ 是代表用户向区块链网络(SUT)提交交易的节点，通常遵循自动化测试脚本。客户端和SUT之间的接口可以从简单的Representational State Transfer (REST)接口到全面的软件开发工具包(SDK)。根据接口的不同，客户机可以是无状态的，也可以是有状态的。
```
A load-generating client is a node that submits transactions on behalf of the user to the
blockchain network (SUT)
```

`on behalf of the user`, 感觉还是 `客户端来代表用户提交交易` 会更准确些。

2021-01-27 16:19 UTC, lijiachuan1982 commented on performance-whitepaper.md
> +区块链是一项新技术，其命名方法每天都在形成和演进。许多常用的软件术语在描述区块链时有了新的细微差别。
```
区块链是一项新技术，其命名方法每天都在形成和演进。许多常用的软件术语在描述区块链时有了新的细微差别。
```

这句话重复了，去掉。我之前看的是网页版的，pdf 的没有这句。你i说的也是这句吧。

2021-01-27 16:23 UTC, lijiachuan1982 commented on performance-whitepaper.md
> +
这块我调整了一下，之前看的网页版，这些都在最后，现在拿到前边来了，跟 pdf 的一样。

2021-01-28 09:53 UTC, SamYuan1990 approved these changes
lgtm

2021-01-28 14:30 UTC, SamYuan1990 commented
@stone-ch , @XuHugo  if your guys also fine with current version, pls merge this pr. thx.

2021-01-28 14:46 UTC, XuHugo approved these changes
ok

2021-01-28 14:49 UTC, merged